
schema_talents = [
    {"name": "id", "type": "STRING", "mode": "REQUIRED"},
    {"name": "time_stamp", "type": "TIMESTAMP", "mode": "REQUIRED"},
    {"name": "subcategory", "type": "STRING", "mode": "NULLABLE"},
    {"name": "geography", "type": "STRING", "mode": "NULLABLE"},
    {"name": "scope", "type": "STRING", "mode": "NULLABLE"},
    {"name": "manager_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_profile_version_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_profile_person_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_profile_talent_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "main_person_email_address", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_first_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_last_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "workspace_id", "type": "STRING", "mode": "REQUIRED"},
    {"name": "person_main_workspace_id", "type": "STRING", "mode": "REQUIRED"},
    {"name": "unit_cost_value", "type": "FLOAT", "mode": "NULLABLE"},
    {"name": "unit_rate_value", "type": "FLOAT", "mode": "NULLABLE"},
    {"name": "staffable", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "entry_date", "type": "DATE", "mode": "NULLABLE"},
    {"name": "exit_date", "type": "DATE", "mode": "NULLABLE"},
    {"name": "role", "type": "STRING", "mode": "NULLABLE"},
    {"name": "person_profile_completion_rate", "type": "FLOAT", "mode": "NULLABLE"},
    {"name": "person_profile_position_start_date", "type": "DATE", "mode": "NULLABLE"},
    {"name": "person_profile_position_end_date", "type": "DATE", "mode": "NULLABLE"},
]
